premise:
    name: Premise
demand:
    name: Demand
    parent_name: premise
supply:
    name: Supply
    parent_name: premise
platform:
    name: Platform
    parent_name: premise
pipeline:
    name: Pipeline
    parent_name: platform
3rd-party:
    name: 3rd Party
