types:
  Type-A:
    name: typea
  Type-B:
    name: typeb
areas:
    A:
        name: A

    B:
        name: B

    AS1:
        name: AS1
        parent: A

    AS2:
        name: AS2
        parent: A

    AS1S1:
        name: AS1S1
        parent: AS1

    Empty:
        name: Empty
components:
    a1:
        name: A1
        level: level_50
        type: Type-A
        team: team-1
        area: A
        release-date: 2016-04-14
        dependencies:
            - a4

    a2:
        name: A2
        level: level_20
        type: Type-A
        team: team-2
        area: AS2
        release-date: 2016-04-14
        dependencies:
            - a3
            - a1

    a3:
        name: A3
        level: level_50
        type: Type-A
        team: team-3
        area: AS1
        release-date: 2016-04-14
        dependencies:
            - a1

    a4:
        name: A4
        level: level_20
        type: Type-A
        team: team-2
        area: AS1S1
        release-date: 2016-04-14
        dependencies:
            - a2
            - b1

    b1:
        name: B1
        level: level_50
        type: Type-B
        team: team-1
        area: B
        release-date: 2016-04-14
        dependencies:
            - b1
levels:
    level_20:
        order: 20
        name: Level 20

    level_50:
        order: 50
        name: Level 50
teams:
    team-1:
        name: Team 1
        team-contact:
            email: team-1@foo.com
        lead-contact:
            name: Lead Contact
            email: lead-1@foo.com
        display:
            background-color: lightblue
            foreground-color: black

    team-2:
        name: Team 2
        team-contact:
            email: team-2@foo.com
        lead-contact:
            name: Lead Contact
            email: lead-1@foo.com
        display:
            background-color: green
            foreground-color: red


    team-3:
        name: Team 3
        team-contact:
            email: team-2@foo.com
        lead-contact:
            name: Lead Contact
            email: lead-1@foo.com
        display:
            background-color: yellow
            foreground-color: black
